### PR TITLE
Flatten Type Class Structures

### LINKED ISSUE #8: Flatten type class structures.
Right now we have structures that look like
```dhall
{ functor : { map : ... }
, applicative : { ap : ..., pure : ... }
, monad : { bind : ... }
}
```
but these should be flattened to
```dhall
{ map : ...
, ap : ...
, pure : ...
, bind : ...
}
```
with functions that project out super-instances from sub-instances. With new features like record type combining (`//\\`) and multi-field projection, this will be easier.

As is commonly done in Scala, we should be able to define
```dhall
{ ...
, bind = ...
, traverse = ...
} : Monad ./Foo //\\ Traversable ./Foo
```
in one fell swoop.

### PR DESCRIPTION
**Pull request by zliu41**
Fixes #8

### CODE REVIEW

**Comment by zliu41** [comment]
@sellout is this the approach you wanted? Another approach is to let `Applicative/Type` return `{ap, pure}` only (no `map`), and use `//\\` in all instances, e.g., `List/Applicative` would return `Applicative List //\\ Functor List`. But by doing so we need to use a lot more `//\\`s, including all arguments like `λ(applicative : Applicative m)` needing to be changed to `λ(applicative : Applicative m //\\ Functor m)`. So I would prefer the current approach, but I wanted to make sure I'm doing the right thing here.

**Comment by robinbb-takt** [comment]
@sell

**Comment by robinbb-takt** [comment]
@sellout It looks like Ziyang might have meant to assign this to you for comment?

**Comment by coreykanon** [comment]
Old PR before Dhall 1.14.
We should trash it or close it out somehow. 
@zliu41

**Comment by FintanH** [comment]
@zliu41 I did this over the weekend at https://github.com/FormationAI/dhall-bhat/pull/19

**Comment by zliu41** [comment]
👌 nice, haven't been able to get to this for ages.

**Pull request closed without merging**
